# Generated by Django 3.0.4 on 2020-04-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tour',
            name='guide',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='season',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
